name: Test & Publish jump-cli-beta

on:
  push:
    tags:
      - 'v*.*.*' # Only publish on version tags like v1.0.3

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for npm OIDC publish

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Run CLI tests
        run: node test.js

      - name: Publish to npm
        if: success() # Only runs if tests passed
        run: npm publish --provenance --access public
