name: CI & Publish (Fixed & Safe)

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show Node & npm versions
        run: |
          echo "=== Node & npm Versions ==="
          node -v
          npm -v
          npm config list

      - name: Install dependencies and run tests
        run: |
          echo "=== Installing dependencies ==="
          npm ci --verbose
          echo "=== Running tests ==="
          node tests.js

  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.actor != 'github-actions[bot]'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (with PAT)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Show Node & npm versions
        run: |
          echo "=== Node & npm Versions ==="
          node -v
          npm -v
          npm config list

      - name: Configure Git for version bump
        run: |
          echo "=== Configuring Git ==="
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config --list

      - name: Install dependencies
        run: npm ci --verbose

      - name: Bump version and push
        id: bump-version
        run: |
          echo "=== Current package version ==="
          cat package.json | grep '"version"'
          echo "=== Bumping patch version ==="
          NEW_VERSION=$(npm version patch --git-tag-version --verbose)
          echo "new_version=${NEW_VERSION#v}" >> $GITHUB_OUTPUT
          echo "=== Git status after version bump ==="
          git status
          git log -n 3 --oneline
          echo "=== Pushing to main ==="
          git push origin main --follow-tags --verbose

      - name: Clean old tags
        run: |
          echo "=== Deleting old Git tags except latest ==="
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          git tag | grep -v "$LATEST_TAG" | xargs -n 1 git tag -d || echo "No local tags to delete"
          git tag -l | grep -v "$LATEST_TAG" | xargs -n 1 git push origin --delete || echo "No remote tags to delete"

      - name: NPM debug info
        run: |
          echo "=== NPM Debug Info ==="
          npm whoami || echo "Token not valid"
          npm config list

      - name: Publish to npm
        run: |
          echo "=== Publishing to npm ==="
          npm publish --verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
          tag_name: "v${{ steps.bump-version.outputs.new_version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List dist folder
        run: |
          echo "=== Contents of dist/ ==="
          ls -la dist/
