name: CI & Publish (Verbose)

on:
  # Run tests on PRs targeting main
  pull_request:
    branches:
      - main
  # Run publish on any push to main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show current directory & files
        run: |
          echo "=== Test Job: Current Directory ==="
          pwd
          echo "=== Listing files ==="
          ls -la

      - name: Show Node & npm versions
        run: |
          echo "=== Node & npm Versions ==="
          node -v
          npm -v
          npm config list

      - name: Install dependencies and run tests (verbose)
        run: |
          echo "=== Installing dependencies ==="
          npm ci --verbose
          echo "=== Running tests ==="
          node tests.js

  publish:
    # Only run this job on pushes to main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show current directory & files
        run: |
          echo "=== Publish Job: Current Directory ==="
          pwd
          echo "=== Listing files ==="
          ls -la

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: https://registry.npmjs.org/
      - run: |
          echo "=== Node & npm Versions After Setup ==="
          node -v
          npm -v
          npm config list

      - name: Configure Git (verbose)
        run: |
          echo "=== Configuring Git ==="
          git config --list
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config --list

      - name: Show current git status
        run: |
          echo "=== Git Status Before Version Bump ==="
          git status
          git log -n 3 --oneline

      - name: Bump version and push (verbose)
        run: |
          echo "=== Current package version ==="
          cat package.json | grep '"version"'
          echo "=== Bumping patch version ==="
          npm version patch --git-tag-version --verbose
          echo "=== Git status after version bump ==="
          git status
          git log -n 3 --oneline
          echo "=== Pushing to main ==="
          git push origin main --follow-tags --verbose

      - name: Publish to npm (fully verbose)
        run: |
          echo "=== Publishing to npm ==="
          npm whoami
          npm publish --verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub release (verbose)
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List dist folder
        run: |
          echo "=== Contents of dist/ ==="
          ls -la dist/
